# IN-CSEが提供するMQTTブローカーの接続URL
cse_broker_urls: 
  - tcp://localhost:1883

# ADN-AEのAE-ID
ae_id: C55DED47A-0aee7e29

# ADN-AEのパスワード
ae_password: EODFOSKGOR

# iRemoconのコマンドを受け渡しするcontainerのURI
ir_commands_container_uri: /HPE_IoT/hgw01/iRemoconCommands

# UIoT PF DAVのホスト名(IP)
dav_hostname: localhost

# UIoT PF DAVのポート番号
dav_port: 8180






spring.datasource.driver-class-name: net.sf.log4jdbc.DriverSpy
spring.datasource.url: jdbc:log4jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
logging.level.jdbc: OFF
logging.level.jdbc.sqltiming: DEBUG